FROM golang:1.24-bookworm

RUN apt-get update && apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

ENV GOOS=windows
ENV GOARCH=amd64
ENV CGO_ENABLED=1
ENV CC=x86_64-w64-mingw32-gcc-posix
ENV CXX=x86_64-w64-mingw32-g++-posix

RUN go build -mod=vendor -ldflags="-s -w -extldflags '-static-libgcc -static-libstdc++ -lpthread'" -o forensiq.exe .
